### ISSUE TITLE
What about persistence? 

### ISSUE THREAD

**Issue by nickl-** [stjohncj/RESTRack#2]
This must be the best kept secret around, you should tell me the secret one day =)

From the documentation it is clear that ActiveRecord found the chopping block but I don't notice any further mention or maybe I'm my quick scan was not thorough enough, with regards to any ORM layer, database or similar persistence support. Will `RESTrack` still generate migration scripts, models, etc? 

@stjohncj please advice...

What is the status of this project, do you consider it production ready? The lack of activity may just mean no one knows your secret but it doesn't help when trying to assess where things are at. Any idea why there's no support? What plans do you have for the project? When can we expect another release update or commit?

**Comment by stjohncj** [comment]
I made the choice to make RESTRack ORM agnostic. You, as the developer, can choose the data persistence layer that suites your development and application needs.  It would be the responsibility of the ORM to generate migration scripts etc.  ActiveRecord can be used.

As for the status of the project, yes I do consider it to be production ready.  I have made commits earlier this year, and will be releasing a "2.0.0" version sometime in the near future (which will likely be documentation of and a formal wrapping on the features and bug fixes implemented since the 1.0 release.  The current state of the software seems to be very stable, and I try to respond to any bug reports within a few hours.  I welcome other participants, please don't hesitate to contact me with questions or suggestions or pull requests!

Chris

**Comment by stjohncj** [comment]
I should also point you at the group repo, this one is my personal: https://github.com/RESTRack/RESTRack

Thanks for your interest!

**Comment by nickl-** [comment]
@stjohncj Tx for the reply

### Heads up:

You may want to update https://rubygems.org/gems/restrack and https://www.ruby-toolbox.com/projects/restrack which is what led me (and likely others) here. 

# A BIG Bold NOTICE We've moved to >>> [RESTRack/RESTRack](https://github.com/RESTRack/RESTRack)

on the README for this repo also doesn't hurt.

Will take other friendly suggestions to the pointed at location... tx for the course correction.

On ORM and scope: I agree with agnostic approach but that != out of scope. You cannot do REST without persistance and said that... without cache either. Something to consider.

**Comment by nickl-** [comment]
also link at http://restrack.me/ points here.

**Comment by stjohncj** [comment]
Nick, updated the restrack.me site a while back but neglected to annotate that here.  Thanks again for the "pokes".  Keep the advice coming and I'll try to keep up outside of my "real" job.

pax
